### ISSUE TITLE
Single tilde ("~") command crashes

### ISSUE THREAD

**Issue by louisdh** [holzschu/ios_system#1]
Executing the command `~` crashes at line 760 in `ios_system.m`.
```c
for (int i = 0; i < argc; i++) free(argv_ref[i]);
```

Fwiw, any amount of tildes crashes (e.g. `~~~`).

**Comment by holzschu** [comment]
I'm going to look into it. I did not include that in my tests.

**Comment by holzschu** [comment]
Solution with `f810813`
