### ISSUE TITLE
python: command not found

### ISSUE THREAD

**Issue by bummoblizard** [holzschu/ios_system#106]
Hi holzschu :)
It's my first time trying out ios_system and everything seems to be working fine except python.

I linked python3_ios framework obtained from [here](https://github.com/holzschu/cpython/releases) to the project and transferred the python scripts to the library. For some reason ios_system is not recognising it and always show command not found. What am I missing?

**Comment by holzschu** [comment]
Hi, 
python3_ios has been replaced by cpython: https://github.com/holzschu/cpython/
The latter is easier to update (for the maintainer), has Python 3.9, and provides all packages in a single compilation step.

**Comment by bummoblizard** [comment]
Thanks for the reply! Though I do realise that and is using the xcframework here: [https://github.com/holzschu/cpython/releases ](https://github.com/holzschu/cpython/releases ) 

There's no error message from Xcode what so ever.

**Comment by bummoblizard** [comment]
There is indeed. I copied the configuration from a-shell's `commandDectionary.plist`. Everything works great now! 

> Thanks for the reply! Though I do realise that and is using the xcframework here: [https://github.com/holzschu/cpython/releases ](https://github.com/holzschu/cpython/releases)
> 
> There's no error message from Xcode what so ever. Is there anything I need to modify in `CommandsDictionary.plist`?

**Comment by holzschu** [comment]
Yes (I thought they were in, but apparently not). Also, the releases are outdated (I'm going to remove them). `cpython` generates 1000+ frameworks, so it is difficult to make them available as a github release. I suggest cloning the cpython repository as a submodule and compiling locally. 
```
        <key>python3</key>
        <array>
                <string>python3_ios.framework/python3_ios</string>
                <string>Py_BytesMain</string>
                <string>3bBc:dEhiJm:OQ:RsStuUvVW:xX?</string>
                <string>file</string>
        </array>
        <key>python</key>
        <array>
                <string>python3_ios.framework/python3_ios</string>
                <string>Py_BytesMain</string>
                <string>3bBc:dEhiJm:OQ:RsStuUvVW:xX?</string>
                <string>file</string>
        </array>
        <key>pythonA</key>
        <array>
                <string>pythonA.framework/pythonA</string>
                <string>Py_BytesMain</string>
                <string>3bBc:dEhiJm:OQ:RsStuUvVW:xX?</string>
                <string>no</string>
        </array>
```

**Comment by bummoblizard** [comment]
Hello. I have a follow up question: Do I need to embed all the frameworks generated in `cpython` to my app? Or just the python3, pythonA, pythonB.. etc frameworks?

**Comment by holzschu** [comment]
Hi, you need to add the frameworks requried by the modules you want (so `python*-math.xcframework`, for the `math` module) to the list of embedded frameworks (see "Build phases" -> "Embed Frameworks"). No need to link with them, but they must be embedded.

**Comment by bummoblizard** [comment]
I tried that and it's still not working. Any idea?

**Comment by holzschu** [comment]
I have no idea. Here's what it looks like on my side: 
![image](https://user-images.githubusercontent.com/8070736/103097727-80d41f00-4608-11eb-8f93-bd472894058f.png)

I could maybe understand more with the actual error message.

**Comment by bummoblizard** [comment]
Here's the screenshot and the error message:
![image](https://user-images.githubusercontent.com/38398443/103146079-4f319400-477f-11eb-9736-bcae82fdbea5.png)
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/38398443/103146092-6b353580-477f-11eb-8336-3e5a445f50dd.png">

**Comment by holzschu** [comment]
Hi, 
OK, I see things better now. First, you don't need to link with the python frameworks, only with `ios_system.framework` (you do need to embed them, but apparently you did). Here's what it looks like for me:
![image](https://user-images.githubusercontent.com/8070736/103170044-823c5c00-4841-11eb-91a2-dbef7a106573.png)

Second, it's worth checking if the framework you embedded is actually complete. With `ios_system`, you can issue commands like `ls $APPDIR/Frameworks/python3_ios-math.framework/` and check whether `python3_ios-math` is present.
