### ISSUE TITLE
Consider to bump deployment target to 14

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#108]
Hello, I want you to propose you to bump deployment target to 14, that could reduce memory usage and bundle sizes. (see awesome [wwdc video](https://developer.apple.com/videos/play/wwdc2020/10163/)).

If you are ok with that, I can rebuild all base libs with deployment target 14 instead of 10.

**Comment by holzschu** [comment]
It makes sense ; I'm OK with that since all my apps already have a deployment target of 14, but maybe other users of ios_system could have an issue.
