### ISSUE TITLE
Consider bump openssl dependency to 1.1.1i

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#110]
I prepared [openssl.xcframework v1.1.1i](https://github.com/yury/openssl-apple/releases/tag/v1.1.1i).

It contains bitcode and builded for almost all apple platforms. Minimum versions sdks 14.0 for iOS and tvOS, 7 for Apple Watch, 11 for MacOS. Also it contains almost all architectures. (I removed armv7(s) from iOS since iOS 14 doesn't support 32bit architectures, also I removed i386 architecture from simulators)
Also prepared [libssh2.xcframework v1.9.0](https://github.com/yury/libssh2-apple/releases/tag/v1.9.0) with openssl v1.1.1i dependency.

I tried to compile `ios_system` frameworks with new new `libssh2` and `openssl`. `curls_ios` - compiled without issues, but `ssh_cmd` needed to be updated.

I tried to fix it with new openssl api, but too many fixes and it will took a lot of time for me.
What is original source for ssh? I can try to update from there.

**Comment by holzschu** [comment]
Hi, that would be awesome. I remember that someone else tried to update openssl and encountered issues with curl_ios, so it's good that you went past this one. 

I coded `ssh_main.c` from scratch, based on the example code at: https://www.libssh2.org/examples/

**Comment by yury** [comment]
Sorry, I'm talking about files from [ssh-keygen](https://github.com/holzschu/ios_system/tree/master/ssh_keygen) folder.

**Comment by holzschu** [comment]
In that case, it seems to be from OpenSSH 7.5, possibly through Apple OpenSource repository :  https://www.openssh.com/openbsd.html

There are minimal differences between `ssh-keygen.c` in OpenSSH 7.5 and `ssh-keygen.c` in the `ssh-keygen` folder.
