### ISSUE TITLE
Running multiple commands at a time

### ISSUE THREAD

**Issue by bummoblizard** [holzschu/ios_system#116]
Hi again, @holzschu. Thanks again for helping me setting up the Python environment at #106 ! 

Since it's possible to run multiple scenes in a-shell, I wonder how we run multiple commands at a time with ios_system. Currently, when I run a long-lasting command in the background queue, all new calls to ios_system() are blocked.

Thanks in advance!

**Comment by holzschu** [comment]
It's a backward compatibility issue. `ios_system` started in a project where there was a single command, so by default the command stops everything until it is terminated. Setting the global variable `joinMainThread` to `false` breaks this behaviour, so you can run multiple commands at the same time. 
Of course, it's up to you to make sure you keep their environment running until they are done. `pid = ios_fork()` and `ios_waitpid(pid)` will help.

**Comment by bummoblizard** [comment]
Great! It works now. It's actually a rather interesting use case. I am able to setup a python language server with `ios_system`.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/38398443/107541776-7266b480-6c02-11eb-866a-48156c66008e.png">

thebaselab/codeapp#29

**Comment by holzschu** [comment]
Great app, and cool application. Do you want me to add it to the list of apps using ios_system at https://github.com/holzschu/ios_system/ ?

**Comment by bummoblizard** [comment]
Sure!
