### ISSUE TITLE
Calling ios_kill() may cause a crash

### ISSUE THREAD

**Issue by 12345CPZ** [holzschu/ios_system#134]
Hi, @holzschu . I am trying to call pdflatex with ios_system framework. It works fine. However, when compiling large files, if I call the ios_kill method to end the compilation, the application crashes. 
<img width="1120" alt="1" src="https://user-images.githubusercontent.com/106484439/179352996-abf233c3-9041-4932-a5ea-7bd48ffe1d26.png">
The problem may be in line 1963 of ios_system.m. There is something wrong with the function pointer of the signal handler.

**Comment by 12345CPZ** [comment]
After looking up some information, I found that it is not safe to call signal handlers after dlclose().

**Comment by holzschu** [comment]
Yes, but `ios_kill` is called before pdftex is terminated, so it is called before `dlclose()`.

Some function or command has registered a signal handler for `SIGINT`, with the pointer `0x13797563c`. The question is who, and why was it not updated?

**Comment by 12345CPZ** [comment]
It works fine! Thank you.

**Comment by holzschu** [comment]
Out of curiosity, are you using the patched source at https://github.com/holzschu/texlive-source?

**Comment by holzschu** [comment]
`lib-tex` is an old repository (based on texlive-2019), you should use `texlive-source`: https://github.com/holzschu/texlive-source which is based on texlive-2022. Build instructions are the same. 

You even have precompiled binaries here: https://github.com/holzschu/texlive-source/releases/tag/texlive-2022 but obviously they don't have the recent bug fix yet.
