### ISSUE TITLE
ios_system should return non-zero exit code on "command not found"

### ISSUE THREAD

**Issue by IMcD23** [holzschu/ios_system#14]
When passing a gibberish string to ios_system, it prints "command not found" to stderr, but returns 0, meaning it was successful. This does not match what other shells do when commands are not found. 

I tested Bash and Fish to see what they do, and they both return 127 when no command is found.

**Comment by holzschu** [comment]
Fixed with release 169e0d7 in the branch dynamicLibraries.

**Comment by holzschu** [comment]
Merged into the main branch. Release 1adfc59 has this.
