### ISSUE TITLE
### Board

### ISSUE THREAD

**Issue by Talaljameel** [holzschu/ios_system#141]
### Board

Lolin ESP32-S3 mini

### Device Description

ESP32-S3

### Hardware Configuration

no gpio in use

### Version

latest master (checkout manually)

### IDE Name

CLION

### Operating System

Windows 11

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

esptool.js does not work with TinyUSB devices like S2 and S3,
https://github.com/espressif/esptool-js/issues/97
this means that you cannot flash this devices using a web tool when they are in TinyUSB mode.

as you can imagine TinyUSB is much better than CDC since CDC creates lags on S3, it consumes more memory and it's not as stable as TinyUSB.

is there a way to flash a CDC firmware using the esptool.js and then switch to TinyUSB at runtime using some lines of code inside our firmware?

### Sketch

```cpp
no sketch
```

### Debug Message

```plain
no debug
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

_Originally posted by @sblantipodi in https://github.com/espressif/arduino-esp32/issues/8277_

**Comment by sblantipodi** [comment]
yes that was a issue I opened on the espressif repo. weird.
