### ISSUE TITLE
Handle files with spaces better

### ISSUE THREAD

**Issue by louisdh** [holzschu/ios_system#18]
louisdh/terminal/issues/74

**Comment by holzschu** [comment]
Solved with commit 3d8d7f8 on the experimental branch. 
![dyhvkviwkaavnzk jpg-large](https://user-images.githubusercontent.com/8070736/37307817-68f7db90-263c-11e8-8956-9ea42cb3d84b.jpeg)

**Comment by holzschu** [comment]
See also commit 5d83d58 of master branch.
