### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by louisdh** [holzschu/ios_system#20]
Travis CI is free for open source projects. Setup is pretty easy, and the benefits are great.

Setup:
• Add .travis.yml file to the root of this project (example: https://github.com/louisdh/terminal/blob/master/.travis.yml)
• Go to https://travis-ci.org, log in with GitHub and enable this project

**Comment by holzschu** [comment]
Done for iOS_system and libssh2 (see https://github.com/holzschu/libssh2-for-iOS). Required some changes in the Xcode project to make sure we only access local files. Do you want me to propagate those changes to the version of iOS_system in OpenTerm?
