### ISSUE TITLE
Support for UTF-8 encoding

### ISSUE THREAD

**Issue by IMcD23** [holzschu/ios_system#21]
OpenTerm passes UTF-8 commands to ios_system, and expects UTF-8 output from commands. However, argument parsing & command parsing converts the string to ASCII, which causes data loss.

Try: `echo 😀` in OpenTerm to see results.

**Comment by holzschu** [comment]
That is a very good question. I'll look into it, but most Unix commands expect a C-string as input. There might not be a way to keep UTF8 characters through the entire pipeline. 

At some point, the arguments have to be `(char argc, char **argv)`. I do not know of a way to do UTF8 -> char -> UTF8 while keeping UTF8 information. I'll have to learn.

**Comment by IMcD23** [comment]
`-[NSString cStringUsingEncoding:NSUTF8StringEncoding]`?

**Comment by holzschu** [comment]
Sorry, strike my previous answer. `ios_system()` operates on `char*`, because `system()` operates on  `char*`. There is no operation on the encoding inside `ios_system()`. The conversion was done in `CommandExecutor`, where there is the line `ios_system(command.utf8CString)` which is equivalent to `[command cStringUsingEncoding:NSUTF8StringEncoding]` (but shorter). 

We need to track the result of this `command.utf8CString` conversion, but my guess is that it removed the UTF-8 content to make it compatible with C-like strings. This conversion cannot be reversed.

**Comment by IMcD23** [comment]
Take a look at ‘parseArgument’. You’re converting the arguments to ASCII.

**Comment by IMcD23** [comment]
All that should be necessary to fix this (I've verified locally) is to change all occurrences of `NSASCIIStringEncoding` to `NSUTF8StringEncoding` in `ios_system.m`

[diff.txt](https://github.com/holzschu/ios_system/files/1704708/diff.txt)

However, if we want to support other encodings than UTF-8 in the future, more work would be needed.

**Comment by holzschu** [comment]
You're absolutely right. It works now. Gonna make a short PR for that. 
The effects are... interesting. Not all commands work, but most of them do. 
![img_1160](https://user-images.githubusercontent.com/8070736/35941777-b58ca7cc-0c53-11e8-8c8e-e1a78bf4b35b.jpg)

**Comment by IMcD23** [comment]
Looks like `ls` fails, that's it? Overall, looks like a nice improvement to what we currently have.

**Comment by IMcD23** [comment]
Investigating `ls`. Looks like the relevant code is at `file_cmds_ios/ls/util.c` line 113. `iswprint(wc)` fails, so it prints a `?`

**Comment by holzschu** [comment]
According to the doc, it should reply true if the character is printable, according to the defined locale: http://en.cppreference.com/w/c/string/wide/iswprint

**Comment by IMcD23** [comment]
Do we need to define `LANG`, `LC_ALL`, etc?

**Comment by holzschu** [comment]
Defining `LC_ALL` to `en_US.UTF-8`: doesn't work. 
Calling `setlocale(LC_ALL, "en_US.UTF-8")` in `iOS_system.m`: doesn't work.
Calling `setlocale(LC_ALL, "en_US.UTF-8")` in `ls.c`: doesn't work.
It does work on my mac.

**Comment by IMcD23** [comment]
What does `setlocale(LC_ALL, NULL)` return? That should get you the current locale that C is using.

**Comment by holzschu** [comment]
It says "C", which explains the behaviour of `iswprint` but is inconsistent with the `LC_ALL`.

**Comment by holzschu** [comment]
Fixed with  6c22c28. I guess I can close this issue now?
