### ISSUE TITLE
Add ssh-keygen

### ISSUE THREAD

**Issue by IMcD23** [holzschu/ios_system#23]
Not sure which OpenSSH we are using, but it'd be great if we could get the ssh-keygen utility to generate SSH keys.

[Source](https://opensource.apple.com/source/OpenSSH/OpenSSH-7.1/openssh/ssh-keygen.c)

**Comment by holzschu** [comment]
We are using OpenSSL and libssh2. ssh-keygen does not seem to work with libssh2. I do not know how to generate keys using libssh2, but I can see the question has been asked frequently before. Right now, the solution is to generate the keys elsewhere, but it's not fully satisfying.

**Comment by holzschu** [comment]
I was looking in the wrong place. Keygen is done with openssl. For reference: https://stackoverflow.com/questions/5927164/how-to-generate-rsa-private-key-using-openssl

I'm going to get a second look at this.

**Comment by holzschu** [comment]
I have a working version of ssh-keygen in a2d0b02. 
Entering a passphrase for the key doesn't work, as it depends on `readpassphrase`, which reads from `/dev/tty`.

**Comment by holzschu** [comment]
Update: I found an implementation of `readpassphrase`, so the user can enter a passphrase for their key. I need a way to turn off local echo before this makes it into the main release.

**Comment by IMcD23** [comment]
Looks like most things use tcsetattr to disable echo. We’ll have to see if that works on our pipes.

There’s also an escape code: ^[[8m that is not supported in some terminals.

**Comment by holzschu** [comment]
The only secure way to enter a passphrase seems to be to create a pop-up alert, so the string doesn't stay in the terminal buffer. I'll see if I can do that.

**Comment by holzschu** [comment]
Commit 0333099 contains both `ssh-keygen` that asks for a passphrase (using an alert, which solves the local echo issues) and an `ssh` command that: 
- tries connecting without a passphrase,
- asks for a passphrase if the first attempt failed,
- repeats 3 times before giving up.
