### ISSUE TITLE
Update downloaded directories in the .gitignore

### ISSUE THREAD

**Issue by IMcD23** [holzschu/ios_system#25]
Unless I'm doing things wrong here, after checking out the project at master, and running:
* `get_sources.sh`
* `get_frameworks.sh`
* Xcode build

I get a bunch of untracked files in git:
* `ios_system.xcodeproj/xcuserdata/<username>.xcuserdatad`
* `Frameworks/*.framework`
* `curl/*`
* `file_cmds/*`
* `libarchive/*`
* `libinfo/*`
* `libutil/*`
* `shell_cmds/*`
* `text_cmds/*`

I would recommend updating the `.gitignore` file in the repo to ignore these directories.

**Comment by holzschu** [comment]
Thank you very much. I merged your solution.
