### ISSUE TITLE
Add tags 

### ISSUE THREAD

**Issue by drbarrett** [holzschu/ios_system#27]
Just that, ctags would be great.

**Comment by holzschu** [comment]
About halfway through, see https://github.com/holzschu/ctags

**Comment by holzschu** [comment]
This seems to be working now, and consistently produces the same results as the ctags.io test suite. 

You'll have to edit tagbar, so if `executable("ctags")` is `true`, it reverts to the default behaviour. 

Paging @goerz who also expressed interest.

**Comment by drbarrett** [comment]
Fantastic, once this makes it into vim, I can just delete my tag ar fork as it won’t be necessary anymore. I'll try a new build of everything and will let you know how it goes.

**Comment by drbarrett** [comment]
When using the library with iVim:
!ctags --version doesn't return anything which causes the ctags related plugins I've tried fail to run. 

![img_0060](https://user-images.githubusercontent.com/408923/37741047-578a08d2-2d36-11e8-8876-fcd9b86a0a5b.JPG)

**Comment by holzschu** [comment]
I don't have that issue :
![img_0077](https://user-images.githubusercontent.com/8070736/37743319-daff47b2-2d69-11e8-8d48-e9cee0739476.jpg)

Now the question is why do you have it. Did you install 'libctags.dylib' (precompiled version in https://github.com/holzschu/ios_system/releases/ or source code in: https:/ /github.com/holzschu/ctags ) ? Is 'libctags.dylib' in the list of embedded frameworks for iVim? 

What happens if you type `:!ctags --version` in command mode?

**Comment by drbarrett** [comment]
OK
- Fresh install of the master branch of your fork of iVim
- Run get_frameworks.sh
- run my script that swaps ID strings
- load project

ctags was not in the list of libraries. Neither was libcrypto.a or libnetwork_ios.dynlib. See the screenshot below. I added all 3 and rebuilt. Now I'm getting this error in the xcode console when trying to run on the ipad:

dyld: Library not loaded: /Users/holzschu/Library/Developer/Xcode/DerivedData/ctags-aovmzpjnmpbrpggjgpnpxaoietzg/Build/Products/Debug-iphoneos/libctags.dylib
  Referenced from: /var/containers/Bundle/Application/AC76E0F7-2E99-4807-86E9-70BF3A2986B8/iVim.app/iVim
  Reason: image not found

Guessing I'll need to try building the framework from source and try again.

![screen shot 2018-03-22 at 12 02 28 pm](https://user-images.githubusercontent.com/408923/37782495-6172f9ce-2dc9-11e8-90d6-34fe6dda3d5a.png)

**Comment by holzschu** [comment]
Thanks a lot. There must be an issue with the project file. I'm going to do a fresh clone and see what I can do.

**Comment by holzschu** [comment]
Short version: the latest commit (a4855c4) should fix that. I had not committed a recent version of the project file. Terribly sorry about that. 

Long version: in addition to being in the left column, the dynamic libraries that contain the commands must also be added to the list of "Embed Frameworks" in "Build phases" (but they don't need to be in "Link binary with libraries", except for lua, python and ios_system).

**Comment by drbarrett** [comment]
Now it won't compile because it can't find pyconfig.h. I don't see anything in the diffs that should have affected this. I need to do my actual work, so I'll come back and look at this later.

**Comment by holzschu** [comment]
Thank you for pointing this out. I added the "-I../ios_python" to the flags of if_python.c in commit  3654b5b.
