### ISSUE TITLE
ls ~/tmp causes crash

### ISSUE THREAD

**Issue by drbarrett** [holzschu/ios_system#31]
This is with a build of your fork of iVIm.

running
:!ls ~/tmp

displays the directory contents, then crashes the app after hitting return.

**Comment by holzschu** [comment]
You're right. Also "~" does not point to the value of `$HOME`. This is weird. I'm going to have a look at that one too.

**Comment by drbarrett** [comment]
Ah right ~ in iVim is the Documents folder, but the ios_system stuff uses the parent directory.

I just tried echo $HOME on OpenTerm, and it returns the parent folder even though it doesn't let you go outside of the Documents folder.

$HOME and ~ should probably point to Documents and maybe use / for the parent directory although that'll probably cause other problems.

**Comment by holzschu** [comment]
The system (iOS) defines $HOME. I assume it does so for a reason, so I'd rather not touch it.

But I agree that "cd ~" should go to the Documents folder and that ios_system should follow what the host app says. I replaced all calls to `stringByExpandingTildeInPath` with calls to `stringByReplacingOccurrencesOfString` and the crash appears to have disappeared.
