### ISSUE TITLE
request for pbcopy and pbpaste

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#35]
I think it will be nice :)

**Comment by holzschu** [comment]
That looks quite easy. I'm on it.

**Comment by louisdh** [comment]
Fyi: OpenTerm already has pbcopy and pbpaste.

**Comment by holzschu** [comment]
Done with commit 119b147, in a way that doesn't interfere with OpenTerm's pbcopy / pbpaste (but can replace them if you want).
