### ISSUE TITLE
whois command

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#40]
I found this command useful.

I tried to port it myself this time.

This command is in `adv_cmds`, don't find it framework.
so, I test it with in files.framework

And I don't get how to create patch file.
So this is my [whois.c file](https://gist.github.com/yury/20aba09e0fddb1746612181a4c06c7fb)
I hope it helps.

**Comment by holzschu** [comment]
Awesome work! I have incorporated it into network_ios. Thank you very  much!

I've also added `libc_replacement.c` to `ios_system.framework`. Makes it easier to port new commands: it contains replacements for printf, err, errx, warn, warnx, write...

**Comment by holzschu** [comment]
Yes, you can close them.

**Comment by yury** [comment]
Hi @holzschu,

Can you update build network_ios.framework with this command?

**Comment by yury** [comment]
@holzschu thanks. Maybe false alarm :). Rechecked now it is ok.
