### ISSUE TITLE
request for md5

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#41]
I found this command in text_cmds, but did get how to port common crypto part.

**Comment by holzschu** [comment]
Yes, I can't get it to compile either.

**Comment by yury** [comment]
Hi, @holzschu.

Here is working md5 https://gist.github.com/yury/a6dc9dcc85c211b384fdf996e3975a57

**Comment by yury** [comment]
Hi @holzschu,
Quick question. Should flags be `__thread` instead of static in `cat.c`?

**Comment by holzschu** [comment]
Hi @yury, 
yes, they should. Actually, they should be both `__thread` and `static`. I just changed that, I'm going to commit and push the change. It's not a big deal unless two different terminals are starting `cat` at the same time. 

You did a beautiful work of porting md5. It works straight out of the box. It even works through pipes (try `cat history.txt | md5`)

About `md5` without args (and other commands without args): All these commands are listening to `thread_stdin`. And we set `thread_stdin` to `_stream.in`, so they're listening to `_stream.in`. But it seems that keyboard input is not forwarded to `_stream.in` and thus to `thread_stdin`. You did something specific for control-C and control-D. Could you extend that to other keys? And maybe print them on `stdout` as well, before sending them to `thread_stdin`?

**Comment by yury** [comment]
Hi @holzschu,

I can see what I typed after `cat` without args (one line). In `md5` without args I can't see anything.
And after that, `cat` without args stops working too.

So I messed up somewhere with thread, I think. (that is what I'm trying to say)

**Comment by holzschu** [comment]
Hi @yury, 
First, it's great that it works (in the sense that it wrote into `file.txt`). 
The fact that you see nothing on the console needs to be addressed inside Blink. 
Right now, you have a pipeline: 
`(letter typed on keyboard) -> stdin -> thread_stdin -> cat command -> file.txt`
And you would like:
```
(letter typed on keyboard) -> stdin -> thread_stdin -> cat command -> file.txt
                           \-> stdout -> display on screen
```
That is, you need to duplicate the input stream, so that the things that the user writes on the keyboard go both to the command (through thread_stdin) and to the Blink output.

**Comment by yury** [comment]
Got it, thank you.

**Comment by holzschu** [comment]
Hi @yury, 
I'd like to try that. On which fork of blink is it?

What do you mean by "control"?
