### ISSUE TITLE
"Use of undeclared identifier 'SORT_VERSION'" in sort.c

### ISSUE THREAD

**Issue by louisdh** [holzschu/ios_system#42]
I'm getting ```Use of undeclared identifier 'SORT_VERSION'``` when trying to compile the latest ios_system master (with the sort command) in OpenTerm.

**Comment by holzschu** [comment]
That's odd. Lines 3026 to 3028 of `text_cmds.patch` should say:
```
+//#ifdef __APPLE__
+//				printf("%s (%s)\n", VERSION, strlen(SORT_VERSION) ? SORT_VERSION : "0");
+//#else
 ```

**Comment by louisdh** [comment]
Oh, I should probably re-run the `get-frameworks` script.
