### ISSUE TITLE
bpcopy crash

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#44]
Hi @holzschu,

In blink `cat known_hosts | bpcopy` works fine, but `cat keys | pbcopy` crashes because it tries to set `nil` to `[UIPasteboard generalPasteboard].string`

It is better to collect all input in NSData first, because we can hit incomplete utf-8 char on buffer end.

Here is more safe version:
https://gist.github.com/yury/7a99c559e7b687a861b2f40cba67bbc1

**Comment by holzschu** [comment]
Hi @yury, 
Makes sense. Merged in the code (commit  47b454a) and... placed in the release, which still has the number 2.0.
