### ISSUE TITLE
feature request for thread context.

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#46]
I want to port all blink commands to ios_system commands.

Simple commands like `help`, `config` are ok. But some commands, like ssh, mosh need some sort of thread state. 

I'm thinking about `ios_setContext(void * thread_context)` same as `ios_setStreams`. So it would be possible to grab that context inside the commands.

Does it make sense? If idea is acceptable, I can do PR for that.

**Comment by holzschu** [comment]
Hi @yury, 
that sounds like you're starting something ambitious and difficult. 
I have no problems with what you suggest.

**Comment by yury** [comment]
Hi @holzschu,
here is PR #47

**Comment by yury** [comment]
Thank you!
