### ISSUE TITLE
Can't compile current iVim

### ISSUE THREAD

**Issue by goerz** [holzschu/ios_system#52]
I'm having trouble compiling the latest `master` version of [iVim](https://github.com/holzschu/iVim)
I'm doing the [same steps that worked before](https://michaelgoerz.net/notes/editing-latex-on-the-ipad-with-ivim.html). The compilation ends with the error message
~~~
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/goerz/Documents/Programming/iVim/iVim
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name iVim -Onone -enforce-exclusivity=checked -DDEBUG -sdk [...]

<unknown>:0: error: no such file or directory: '/Users/goerz/Documents/Programming/iVim/iVim/URLRealizer.swift'
<unknown>:0: error: no such file or directory: '/Users/goerz/Documents/Programming/iVim/iVim/ArgumentToken.swift'
<unknown>:0: error: no such file or directory: '/Users/goerz/Documents/Programming/iVim/iVim/URLOpener.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
~~~

The swift files it complains about are actually in `/Users/goerz/Documents/Programming/iVim/iVim/iVim` (an extra `iVim`). I've tried copying the entire content of that directory up one level, to the path where Xcode seems to be asking for.

This gets me further in the compilation, but then the linker fails with
~~~
ld: illegal data reference in _Py_NoSiteFlag to thread local variable _Py_NoSiteFlag in dylib /Users/goerz/Documents/Programming/iVim/iVim/Frameworks/Python_ios.framework/Python_ios for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~
Any ideas?

**Comment by holzschu** [comment]
The issue with Py_NoSiteFlag was with Python_ios. I've pushed a fix on both python_ios and iVim. It should compile now (you might have to download the frameworks latest release if you don't compile them).

**Comment by goerz** [comment]
The `get_frameworks.sh` script should be downloading everything I need, right? It looks like `libnetwork_ios.dylib` is missing (although there is a `network_ios.framework` in `Frameworks`)

Compilation ends with the message

~~~
error: /Users/goerz/Documents/Programming/iVim/iVim/Frameworks/libnetwork_ios.dylib: No such file or directory
~~~

**Comment by holzschu** [comment]
I forgot to move network_ios from a dylib to a framework in the Xcode project. Can you update and retry?

**Comment by goerz** [comment]
That works! I was able to compile iVim. Thanks for you help!

For some reason, it doesn't like my configuration though (it freezes and then crashes when I open any file). If I disable my vimrc/.vim folder, it works fine, though. Maybe a plugin relying on ctags? I'll be traveling next week, so I won't have a chance to look into it further, but I might get in touch again after that ;-)

**Comment by holzschu** [comment]
There was a different issue to be fixed (related to waitpid, not related to the crash). You should update ios_system.framework. 
I'm interested in the cause for the crash.

**Comment by goerz** [comment]
I'll look into it next week! Thanks again!
