### ISSUE TITLE
rlogin: command not found

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#59]
It is listed in [commandDictionary.plist](https://github.com/holzschu/ios_system/blob/master/Resources/commandDictionary.plist#L257). But I could find implementation in network_ios.

**Comment by holzschu** [comment]
That was a bug in commandDictionary.plist; `rlogin_main` should be `telnet_main` (it is the same executable, behavior depends on argv[0]).

**Comment by yury** [comment]
thank you
