### ISSUE TITLE
Need to chose a license for ios_system (and the rest)

### ISSUE THREAD

**Issue by holzschu** [holzschu/ios_system#61]
I just realized I did not pick a license for the common parts of ios_system. The utilities themselves (mkdir, ls, pwd...) are covered by their original license (Free BSD, mostly). But the "glue" code (`ios_system.m` and the other files) is currently not covered, which is a very bad idea. 

I'm open to suggestions. I'm leaning towards a revised-BSD license (3 clause BSD license). 

Those of you who contributed to the code: @yury, @louisdh, @IMcD23, @palmin, @pducks32 : any opinion about the type of license?

**Comment by palmin** [comment]
My contribution consists entirely of moving out declarations to the public interface.
I'm fine with whatever you come up with. 😄

**Comment by yury** [comment]
I'm ok with revised-BSD license (3 clause BSD license)

**Comment by holzschu** [comment]
I've placed the repository under the revised-BSD license (3 clause BSD license).
