### ISSUE TITLE
Proposal: remove coordinateWritingItemAtURL lock 

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#64]
Hi @holzschu,

This [lock](https://github.com/holzschu/ios_system/blob/master/ios_system.m#L1292) prevents to new ssh (ios_system based) commands to run within same folder. 

May be we can remove that lock for now and try to coordinate writes on commands level?

Thank you.

**Comment by holzschu** [comment]
Hi @yury, 
the `coordinateWritingItemAtURL` is there to inform other apps that the directory content has been modified (so they update their own views). It is useful when, say, pdfViewer is displaying a PDF and blink changes the PDF. Or Files is displaying a folder and blink creates a new file inside. It's not gonna be easy to remove.

The lock is not activated if the command does not operate on files or directories (as defined in the plist file), meaning you can deactivate it on a per-command basis.

**Comment by yury** [comment]
Thank you. Move command to plist and set operation on to 'no'.
