### ISSUE TITLE
Command line parsing system doesn't handle `>` inside quotes right

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#68]
In the zsh:

 ```sh
ssh localhost "echo nice; ls -la" 1>/dev/null
# outputs nothing
```

```sh
ssh localhost "echo nice; ls -la 1>/dev/null"
nice
```

In the blink, which is using ios_system for executing commands:

```sh
ssh -q office "echo nice; ls -al"1>/dev/null
# outputs nothing
```

```sh
ssh -q office "echo nice; ls -al 1>/dev/null"
zsh:1: unmatched "
```

Refs blinksh/blink/issues/203

**Comment by holzschu** [comment]
Ah. I see where that comes from (`ios_system.m` is parsing ">" before parsing for quotes). 

I should add a test for quotes when parsing for ">".
