### ISSUE TITLE
Wrong patch for curl

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#71]
Hi @holzschu,

sorry, but I did make mistake with the patch to curl 

[This line](https://github.com/yury/ios_system/blob/491d8d5209753d71c6778f14b4ff26ff93623872/curl.patch#L814) should not be in the patch.

Correct code is `return result;`

**Comment by holzschu** [comment]
Thanks for this correction!
The latest version has the fix, with "return result". (4de09f4 and  d94b507).

**Comment by yury** [comment]
Sorry for that :(

Thank you for fast fix.
