### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ColdGrub1384** [holzschu/ios_system#72]
Hello. Do you plan to release a new version? I use pre-built frameworks.

**Comment by holzschu** [comment]
Yes, I am working on it.

**Comment by ColdGrub1384** [comment]
Ok, thank you!

**Comment by holzschu** [comment]
Done with release 2.2: https://github.com/holzschu/ios_system/releases

**Comment by ColdGrub1384** [comment]
Thank you!
