### ISSUE TITLE
request: say command

### ISSUE THREAD

**Issue by yury** [holzschu/ios_system#74]
And here is an implementation.

https://gist.github.com/yury/66b3e4377a530f6739d2f3327700ee64

**Comment by holzschu** [comment]
Added and committed, but it remains silent on my devices.
It goes through the line `[synth speakUtterance:utterance];` but nothing comes out.

**Comment by holzschu** [comment]
It's probably related to my settings, since I can't get OpenTerm to speak either (they have a different implementation).

**Comment by holzschu** [comment]
Found the issue: my phone was in silent mode (the physical button on the side).

**Comment by yury** [comment]
Hmm interesting, what ‘say -v “?”’ outputs?

**Comment by yury** [comment]
Got it
