### ISSUE TITLE
open command

### ISSUE THREAD

**Issue by ColdGrub1384** [holzschu/ios_system#77]
There is an `openurl` command that opens an URL. But, wouldn't be better an `open` command that would detect if arguments are URLs or file paths? So if the argument is file path, it opens an `UIActivityViewController` and if it's an URL, it opens it. Something like that: https://github.com/ColdGrub1384/LibTerm/blob/master/LibTerm/Commands/open.swift. 

I can submit a pull request (without removing @yury changes), but I prefer asking to you first to see if you like the idea.

**Comment by holzschu** [comment]
Thank you for the suggestion. That is a great idea. @yury, do you have any objection? 

(I needed `openurl` specifically for Jupyter, but that project has now moved to its own repository)

**Comment by yury** [comment]
No, I'm ok with that. Good idea.
