### ISSUE TITLE
using openTerm on my iPad

### ISSUE THREAD

**Issue by passereve** [holzschu/ios_system#9]
Hi !

I am not able to go around that ‘permission denied’ 👎 

Could you give me a hand ?

Thanks for your job !
Regards, François

iPad de François: ls
iPad de François: cd /
cd: /: permission denied

iPad de François: date
Sat Jan 20 13:33:01 CET 2018

iPad de François: ?
awk, cat, cd, chflags, chksum, clear, compress, cp, curl, date, du, echo, egrep, env, fgrep, grep, gunzip, gzip, help, link, ln, ls, mkdir, mv, printenv, pwd, readlink, rm, rmdir, scp, sed, setenv, sftp, stat, sum, tar, touch, tr, uname, uncompress, unsetenv, uptime, wc, whoami

iPad de François: cd ..
cd: ..: permission denied

iPad de François: login
login: command not found

iPad de François: man ls
man: command not found

iPad de François: uname
Darwin

iPad de François: whoami
mobile

iPad de François: cd /var
cd: /var: permission denied

iPad de François: cd /var/mobile
cd: /var/mobile: permission denied

iPad de François: cd /var/mobile/Containers
cd: /var/mobile/Containers: permission denied

iPad de François: cd /var/mobile/Containers/Data
cd: /var/mobile/Containers/Data: permission denied

iPad de François: cd /var/mobile/Containers/Data/Application
cd: /var/mobile/Containers/Data/Application: permission denied

iPad de François:

**Comment by holzschu** [comment]
All of that is normal. The OpenTerm application, to be acceptable for the AppStore, respects the sandbox boundaries. So changing directory outside the boundary of the app sandbox is impossible.

If you are sideloading, you can disable the "setMiniRoot" line in the OpenTerm source code. Note that it won't change much. `cd /` is permitted, but not `cd` into any of the directories below `/`. `cd ..` is permitted, but only once. All the others are still forbidden (the user `mobile` does not have reading rights for these directories).

What is it that you were trying to do?

**Comment by passereve** [comment]
opening /folders/ then cmd ls -ln

**Comment by passereve** [comment]
So I understood that I am just allowed to create new folders to write new files, isn’t it ?

**Comment by holzschu** [comment]
Yes. You can also download them (with curl), move them around (with the Files app), edit them (with other apps). But always inside the sandbox.

**Comment by passereve** [comment]
Thank you
By the way this is already great 👍 
Thanx again for your job !
François

**Comment by holzschu** [comment]
Can I close this issue?

**Comment by passereve** [comment]
Yes 👍
Thanks
--
