### ISSUE TITLE
Request for file

### ISSUE THREAD

**Issue by kkk669** [holzschu/ios_system#97]
If nobody is working on it, I'll try to compile from the source on [Apple OpenSource](https://opensource.apple.com/source/file/file-74.0.2/).

However, the latest version of [iVim](https://apps.apple.com/us/app/ivim/id1266544660) already did it, so if @terrychou is going to backport it to this repository, I'll wait for that.

**Comment by terrychou** [comment]
I have pushed the code up to Github, you can check it out: https://github.com/terrychou/file_ios
