### ISSUE TITLE
Request for any Wake On Lan Tool

### ISSUE THREAD

**Issue by pr1metine** [holzschu/ios_system#98]
Something like  `etherwake` or `wakeonlan` would be much appreciated. This way [Blink](https://github.com/blinksh/blink/issues/951) can add WOL Support.

**Comment by holzschu** [comment]
I'll have a look. I assume this is to wake up other computers, not to wake up your own iPad?

**Comment by pr1metine** [comment]
Yes, the Tool should wake up another computer. Is it even possible to wake up an iPad?

**Comment by instinctive** [comment]
Yes this would be very useful... right now I have to wake my powerhouse linux system via the anemic mac mini on the same network:

    blink> ssh mymac '/usr/local/bin/wakeonlan -f mylinux.eth'

**Comment by holzschu** [comment]
Hi, just checking. I'm looking for source code for either commands. I found this: https://github.com/gumb0/wol.cpp
Does it fit your needs?

**Comment by pr1metine** [comment]
LGTM. Forgive me for this noob question:

When using [wol.cpp](https://github.com/gumb0/wol.cpp), is there a way to wake up a device based on its hostname?

**Comment by holzschu** [comment]
Hi,
wake-on-lan (wol) has been added to the latest release of network_ios: https://github.com/holzschu/network_ios/releases/tag/0.2
As far as I can tell, it works with "wol -b 192.168.0.11 aa:bb:cc:dd:ee", i.e. "wol -b <ip address> <MAC address of device>". 
And you'll have to provide the IP address, not the hostname, but you can get it from the hostname using nslookup.
