### ISSUE TITLE
Support for `ctrl + L` shortcut

### ISSUE THREAD

**Issue by lacf95** [holzschu/ios_system#99]
Just that, be able to use the `ctrl + L` shortcut to clear the screen.

**Comment by holzschu** [comment]
This is more of an issue for the application level. a-Shell, for example, has ctrl+L as a shortcut to clear the screen.

**Comment by lacf95** [comment]
Yeah, I know, but I’m talking about the blink shell session even before login with ssh/mosh to a remote machine

**Comment by holzschu** [comment]
Then, I think, it is an issue for blink.

**Comment by lacf95** [comment]
It is, thanks
